arrowParens: always # It's convenient that you don't have to add them by hand when you need to add more args or a type
singleQuote: true   # Enabled to align with EmberJS Prettier config
printWidth: 100     # Per team's agreement
trailingComma: es5  # Trailing commas makes editing easier, diffs cleaner. `es5` option aligns with EmberJS Prettier config
